2.2.1 创建tensor

In [3]:
import torch

In [4]:
x = torch.empty(5,3)
print(x)

tensor([[3.5733e-43, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [5]:
x = torch.rand(5,3)
print(x)

tensor([[0.6845, 0.4083, 0.1211],
        [0.8210, 0.1422, 0.8452],
        [0.4391, 0.3809, 0.6473],
        [0.8358, 0.1642, 0.9812],
        [0.6835, 0.7942, 0.3302]])


In [6]:
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5,3,dtype = torch.float64)
print(x)

x = torch.randn_like(x,dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 4.2871e-01,  1.6112e+00, -1.2247e+00],
        [-3.0609e-02,  2.0157e-01,  5.5989e-01],
        [-1.5553e+00,  4.0843e-01, -1.4179e-03],
        [ 7.0449e-01, -1.5015e+00, -2.7225e-01],
        [ 1.8102e-01,  1.4003e+00,  1.3651e+00]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
print(x.shape)

torch.Size([5, 3])


2.2.2 基本操作

In [11]:
y = torch.rand(5,3)
print(x + y)

tensor([[ 0.7249,  1.9215, -0.5884],
        [ 0.7972,  1.1584,  0.8663],
        [-0.8344,  0.6013,  0.2691],
        [ 1.1180, -0.7253,  0.6974],
        [ 0.9379,  2.3084,  2.1577]])


In [12]:
result = torch.empty(5,3)
torch.add(x,y,out = result)
print(result)

tensor([[ 0.7249,  1.9215, -0.5884],
        [ 0.7972,  1.1584,  0.8663],
        [-0.8344,  0.6013,  0.2691],
        [ 1.1180, -0.7253,  0.6974],
        [ 0.9379,  2.3084,  2.1577]])


索引 - 索引的结果与原数据共享内存，修改一个，另一个会跟着修改

In [13]:
y = x[0,:]
y += 1
print(y)

print(x[0,:])

tensor([ 1.4287,  2.6112, -0.2247])
tensor([ 1.4287,  2.6112, -0.2247])


改变形状 - 用view来改变tensor的形状

In [14]:
y = x.view(15)
z = x.view(-1,5)
print(x.shape,y.shape,z.shape)

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


view返回的tensor 也是与原来的元组共享tensor的。改变其中的一个，另外一个也会跟着改变。

In [15]:
x += 1
print(x)
print(y)

tensor([[ 2.4287,  3.6112,  0.7753],
        [ 0.9694,  1.2016,  1.5599],
        [-0.5553,  1.4084,  0.9986],
        [ 1.7045, -0.5015,  0.7278],
        [ 1.1810,  2.4003,  2.3651]])
tensor([ 2.4287,  3.6112,  0.7753,  0.9694,  1.2016,  1.5599, -0.5553,  1.4084,
         0.9986,  1.7045, -0.5015,  0.7278,  1.1810,  2.4003,  2.3651])


如果想返回一个真正的副本，不共享data内存。推荐首先使用clone创建一个副本，然后再使用view。

In [16]:
x_cp = x.clone().view(15)
x -= 1

print(x)
print(x_cp)

tensor([[ 1.4287e+00,  2.6112e+00, -2.2466e-01],
        [-3.0609e-02,  2.0157e-01,  5.5989e-01],
        [-1.5553e+00,  4.0843e-01, -1.4179e-03],
        [ 7.0449e-01, -1.5015e+00, -2.7225e-01],
        [ 1.8102e-01,  1.4003e+00,  1.3651e+00]])
tensor([ 2.4287,  3.6112,  0.7753,  0.9694,  1.2016,  1.5599, -0.5553,  1.4084,
         0.9986,  1.7045, -0.5015,  0.7278,  1.1810,  2.4003,  2.3651])


使用colne的好处，梯度传回副本时也会传到tensor

使用item可以将一个标量tensr转换成一个python number

In [17]:
x = torch.randn(1)

print(x)
print(x.item())

tensor([-0.1871])
-0.187078058719635


2.2.3 广播机制 - 适当复制元素到shape相同时进行计算

In [18]:
x = torch.arange(1,3).view(1,2)
print(x)

y = torch.arange(1,4).view(3,1)
print(y)

print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


2.2.4 运算的内存开销

索引操作不会开辟内存，而像y = x+y等操作是会开辟新内存的，然后将y指向新内存。使用id函数，来验证内存地址是否相同

In [19]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])

id_before = id(y)
y = y + x

print(id(y) == id_before) #false

False


如果想写回到原来的y的内存，可以使用索引进行替换 

In [20]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])

id_before = id(y)
y[:] = y + x

print(id(y) == id_before) 

True


注意：
虽然view返回的tensor和原tensor共享data，但是二者的id（内存地址）并不一致，应该是用了某些映射机制。

2.2.5 tensor和numpy之间的相互转换

很容易使用numpy和from_numpy将tensor和numpy数组相互转换。但是需要注意：两个函数差生的tensor和numpy数组也会共享内存，其中一个改变时另一个也会改变。

使用torch.tensor()进行数据拷贝，并且不再共享内存。

In [21]:
a = torch.ones(5)
b = a.numpy()
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [22]:
a += 1
print(a,b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [23]:
b += 1
print(a,b)

tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [24]:
c = torch.tensor(b)
a += 1
print(a,c)

tensor([4., 4., 4., 4., 4.]) tensor([3., 3., 3., 3., 3.])


2.2.6 Tensor on GPU

用to方法可以将tensor在cpu和gpu之间相互移动。

In [25]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device = device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu",torch.double))