In [1]:
import torch
import numpy as np

In [3]:
"""
tensors can be initialized in various ways
"""

# direct from data
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

#from a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# from another tensor
x_ones = torch.ones_like(x_data)
print(f"ones tensor : \n {x_ones} \n")

x_rand = torch.rand_like(x_data,dtype=torch.float)
print(f"random tensor:\n {x_rand} \n")

ones tensor : 
 tensor([[1, 1],
        [1, 1]]) 

random tensor:
 tensor([[0.6152, 0.0799],
        [0.4075, 0.4781]]) 



In [4]:
# with random or constant values
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"random tensor: \n {rand_tensor} \n")
print(f"ones tensor: \n {ones_tensor} \n")
print(f"zeros tensor: \n {zeros_tensor} \n")

random tensor: 
 tensor([[0.5681, 0.3313, 0.6604],
        [0.5391, 0.7454, 0.7426]]) 

ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [6]:
# attributes of a tensor
tensor = torch.rand(3,4)
print(f"shape of tensor : {tensor.shape}")
print(f"datatype of tensor : {tensor.dtype}")
print(f"device tensor is stored on  : {tensor.device}")

shape of tensor : torch.Size([3, 4])
datatype of tensor : torch.float32
device tensor is stored on  : cpu


In [7]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [10]:
tensor = torch.ones(4,4)
print(f"first row : {tensor[0]}")
print(f"first column : {tensor[:,0]}")
print(f"last column : {tensor[...,-1]}")
tensor[:,1] = 0
print(tensor)

first row : tensor([1., 1., 1., 1.])
first column : tensor([1., 1., 1., 1.])
last column : tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
# joining tensors
t1= torch.cat([tensor,tensor,tensor],dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [14]:
#matrix multiplication
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor,tensor.T,out = y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out = z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [15]:
# single-element tensor
agg = tensor.sum()
agg_item = agg.item()
print(agg_item,type(agg_item))

12.0 <class 'float'>


In [16]:
# in-place operations
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [17]:
# tensor to numpy array
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [18]:
# share the same memory
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [19]:
# numpy array to tensor
n = np.ones(5)
t = torch.from_numpy(n)

In [20]:
np.add(n,1,out = n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
